### ISSUE TITLE
How do I install these?

### ISSUE THREAD

**Issue by CarsterX** [adde88/openwrt-useful-tols#12]
Hey, I've been looking for answers online and I can't find out how to install the modules on my mk7.

**Comment by adde88** [comment]
Hi there.
The files in this repo. are not 'modules' for the Pineapple. They are software packages. Which is handled using 'opkg'.
Compare it to the 'apt' tool on Kali / Debian, which dowloads and installs software packages (deb files), usually compiled specifically for your system.

https://openwrt.org/docs/guide-user/additional-software/opkg
