### ISSUE TITLE
* pkg_init_from_file: Malformed package file On any attempt at install on MK7

### ISSUE THREAD

**Issue by CaptainSweatpants** [adde88/openwrt-useful-tols#13]
Can’t seem to install any of these packages on the pineapple MK7. 
_opkg install <ipk file name>_ always returns “ * pkg_init_from_file: Malformed package file....  ”

do these need special handling on the MK7?

Thanks

**Comment by jackgreyhat** [comment]
I've had the same issue...
Are you fetching the packages with wget directly onto the MK7?
Try downloading on your computer and transfering with scp...works perfect that way.

**Comment by ady722001** [comment]
THANKS ....YOU ARE GENTLEMEN

**Comment by adde88** [comment]
Closing this old issue, as it was related to wget corrupting files.
