### ISSUE TITLE
WiFi Pineapple 2.0

### ISSUE THREAD

**Issue by nemanjan00** [adde88/openwrt-useful-tols#20]
Hello,

There is 2.0 in beta and they updated to OpenWRT 21.02.1.

I do not know how your build system works and if it is automated, but if it is trivial, could you release `21.02.1` branch?

**Comment by nemanjan00** [comment]
I am attempting to do it myself, so I will be documenting my progress here, for anyone interested

```bash
git clone https://git.openwrt.org/openwrt/openwrt.git # openwrt source
cd openwrt
git pull
 
git checkout v21.02.1 # pick version specific to firmware you are using

cd ..

git clone git@github.com:pineapple-repo/config.git # my config for mk7 hardware

cd openwrt

cp ../config/.config .

cp feeds.conf.default feeds.conf

# add openwrt-useful-tools feed
echo "src-git openwrt-useful-tools https://github.com/adde88/openwrt-useful-tools-src.git^2576f2f451e8bcd6318bc2ffd39534f1a22f4881" >> feeds.conf

# build and install tools and toolchain
make tools/install
make toolchain/install

# download and index feeds
./scripts/feeds update -a
./scripts/feeds update -i

# generate make for package
./scripts/feeds install bettercap

# build package
make package/bettercap/compile -j32
make package/index
```

Note that this is currently in progress and is not tested

This is the first time I am building openwrt package, so I am not very familiar with build system

Also keep in mind, that `openwrt-useful-tools-src` is not up-to-date with this repo

**Comment by adde88** [comment]
I wasn't aware of any beta-builds, but yes. Adding support for newer releases is quite trivial.
I actually have a snapshot repo / branch locally on the build system as well.
I'll create a new branch, and try to keep it up to date as well :)

**Comment by nemanjan00** [comment]
I am working on automated build system with repo for different architectures and openwrt versions

https://github.com/openwrt-security-repo

It really should be easier to make this more reproducible
