### ISSUE TITLE
Add the hcxpcapngtool utility

### ISSUE THREAD

**Issue by paolosezart** [adde88/openwrt-useful-tols#26]
I installed hcxdumptool on my router. It showed great results. I would like to have the hcxpcapngtool package for the complete package, for quick hash conversion right on the device. Would a respected developer have time to compile hcxpcapngtool for OpenWRT?

**Comment by adde88** [comment]
This program is availble when installing the "hcxtools" package. Either from OpenWRT, or my repo.
