### ISSUE TITLE
bettercap: Pressing Enter causes ^M to appear in terminal

### ISSUE THREAD

**Issue by adde88** [adde88/openwrt-useful-tols#7]
I noticed this 'bug' when i was testing out Bettercap on my Pineapple MK7.
I was SSH'ing into the Pineapple from Putty on my Windows desktop, and i tried running bettercap.
It launched normally. But when i tried to run 'help', i couldn't get the enter button to work as intended. Everytime i tried pushing it **^M** would appear instead. (Screenshot below)
![Screenshot_4](https://user-images.githubusercontent.com/4282828/101919145-85411680-3bca-11eb-8d9b-c9dd1cb8d152.jpg)

I then tried SSH'ing into the Pineapple from my Kali desktop, and the same thing would happen there.
Except, when i pressed 'Control-Enter' it would behave as a normal 'Enter' press.
This "trick" did NOT work when i tried it on my Windows desktop.

I'm not sure what's causing this to happen. I had installed '**coreutils-stty**' on my Pineapple.
And when i checked '**stty -a**' i saw that '**icrnl**' was turned on, as it should be.

**Comment by DeathCamel58** [comment]
Hey @adde88,
I acutally noticed this issue when I built it myself prior to the MK7 update of this repo. I filed an upstream issue report [here](https://github.com/bettercap/bettercap/issues/776)
I noted that it's likely due to `icrnl` being disabled in the console when launching bettercap.
Hope my two cents helps!

**Comment by adde88** [comment]
Thanks for providing more info. I also assumed first it was because of **icrnl** being disabled, but after checking with '**stty -a**' i confirmed that **icrnl** was indeed active. (**coreutils-stty** installed as well).
The reason why 'Control-Enter' didn't work on my Windows desktop is mostl likely related to the SSH client being used, and some tweaks might need to be done there to get that "trick" to work on Windows as well.
But getting to the root-cause of the problem would be even better. :o

**Comment by DeathCamel58** [comment]
Sorry for the delay in response.

The developer recommended trying the `-no-colors` flag with bettercap. This did not resolve my issue. I also updated my build environment to build bettercap 2.29, which has the same issue.

I think there was a bit of a disconnect in our communication, so let me specify what I noticed.

Prior to running bettercap, `icrnl` is enabled.
During bettercap's launch, `icrnl` is disabled, then dropped to bettercap prompt with `icrnl` disabled.
After bettercap is killed, `icrnl` is left disabled.

**Comment by JimmyLaurent** [comment]
The issue should be fixed very soon (refer to the bettercap issue for details), in the meantime you can use [this](https://github.com/adde88/openwrt-useful-tools/files/6056527/bettercap_2.29.1-1_mipsel_24kc.ipk.zip) build.

**Comment by JimmyLaurent** [comment]
Update: It's fixed on the master branch of bettercap.

**Comment by m0bilesecurity** [comment]
Hey @adde88,
are you planning to update bettercap?
Many thanks

**Comment by adde88** [comment]
Yeah, for sure. Life has just been a bit "hectic" lately.
As well as i lost my main desktop SSD drive containing everything i need, so i'm working on getting my poor desktop back to "sanity".
Hopefully in the coming days. :)

**Comment by m0bilesecurity** [comment]
@adde88 take your time! 
Many thanks 👍🏻👍🏻👍🏻

**Comment by adde88** [comment]
This bug should finally be fixed by the latest updates to Bettercap. :)
